#!/bin/sh

### BEGIN INIT INFO
# Provides:          corsa-app-cra
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Corsa CRA controller
# Description:       corsa-app-cra is a controller that accepts 
#                    connections from Quagga's FPM and sends OpenFlow
#                    FIB updates to a Corsa element.
### END INIT INFO

set -e

. /lib/lsb/init-functions

DAEMON=/usr/bin/corsa-cra-app
NAME=corsa-cra-app
DESC="Corsa Routing Adapter"
CRA_OPTS=
PID="/run/$NAME.pid"
LOG_DIR="/var/log/corsa-cra"
LOG="${LOG_DIR}/app.log"

# Check if DAEMON binary exist
[ -f $DAEMON ] || exit 0

CRA_OPTS="--daemon --log-file=$LOG --pid-file=$PID $CRA_OPTS"

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    mkdir -p $LOG_DIR
    if start-stop-daemon --start --quiet --oknodo --pidfile $PID --exec $DAEMON -- $CRA_OPTS 1>/dev/null
    then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    if start-stop-daemon --retry TERM/5/KILL/5 --oknodo --stop --pidfile $PID --quiet 1>/dev/null
    then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting $DESC" "$NAME"
    mkdir -p $LOG_DIR
    start-stop-daemon --retry TERM/5/KILL/5 --oknodo --stop --quiet --pidfile $PID 1>/dev/null
    if start-stop-daemon --start --quiet --oknodo --pidfile $PID --exec $DAEMON -- $CRA_OPTS 1>/dev/null
    then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  status)
    status_of_proc -p $PID $DAEMON $NAME
    ;;
  *)
    log_action_msg "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    ;;
esac

exit 0
